apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: gaia
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-deployment
spec:
  selector:
    matchLabels:
      app: gaia
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gaia
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: gaia-secret
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gaia-secret
                  key: aws-secret-key
          image: klangner/gaia:1.2
          imagePullPolicy: IfNotPresent
          name: gaia
          ports:
            - containerPort: 8080
              protocol: TCP


